# fly.toml app configuration file generated for simonsays-bold-wind-5770 on 2025-03-12T15:45:01-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simonsays-bold-wind-5770'
primary_region = 'ord'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[build]
  dockerfile = "Dockerfile"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
